name: check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Clippy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: arduino/setup-protoc@v1
    - uses: actions/checkout@v4
    - run: rustup component add clippy

    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
